; PlatformIO Project Configuration File — Articulación 2 (brazo robótico 6 GDL)
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
upload_protocol = esp-builtin
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.usb_mode = cdc
board_build.usb_cdc_on_boot = 1
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	olikraus/U8g2@^2.36.12
	robtillaart/AS5600@^0.6.6
